require "directive_admin/gem_ext/formtastic/inputs/base"
require "directive_admin/gem_ext/formtastic/inputs/select_input"
require "directive_admin/gem_ext/formtastic/inputs/jquery_check_boxes_tree_input"
require "directive_admin/gem_ext/formtastic/inputs/jquery_custom_select_input"
require "directive_admin/gem_ext/formtastic/inputs/jquery_date_picker_input"
require "directive_admin/gem_ext/formtastic/inputs/jquery_time_picker_input"
require "directive_admin/gem_ext/formtastic/inputs/jquery_duallistbox_input"
